### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by brianantonelli** [sunfounder/SunFounder_PiCar-S#2]
The SD card that came with my car was blank, I installed the latest version of Raspbian and ran `./install_dependencies` with no issues and rebooted. Afterwards the picar command wasnt found and I discovered that the install from the SunFounder_PiCar repo had silently failed due to setuptools and other modules not being available. After lots of trial and error I found the deps needed were

```
sudo apt-get install -y git \
      python3-setuptools \
      python3-smbus \
      python3-dev \
      python3-rpi.gpio \
      python3-pip
alias python='/usr/bin/python3.7'
```

I then ran `sudo python setup.py install` followed by `picar` and I get:

```
pi@underbellypi:~/SunFounder_PiCar $ picar
Traceback (most recent call last):
  File "/usr/local/bin/picar", line 11, in <module>
    load_entry_point('SunFounder-PiCar==1.0.1', 'console_scripts', 'picar')()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 43, in main
    setup()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 80, in setup
    pwm=PCA9685.PWM(bus_number=1)
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/SunFounder_PCA9685/PCA9685.py", line 121, in __init__
    self.bus = smbus.SMBus(self.bus_number)
IOError: [Errno 2] No such file or directory
```

Any idea whats going on?

**Comment by brianantonelli** [comment]
It looks like the `install_dependencies` script didn't enable `P5 I2C`.. I ran `sudo raspi-config` and enabled `P5 I2C` and then everything worked great.
