### ISSUE TITLE
Picar-S "picar servo-install" doesn't move the servo and command does end

### ISSUE THREAD

**Issue by rizzle95** [sunfounder/SunFounder_PiCar-S#3]
Hi Sunfounder/community 

I have an issue with a new PiCar-S. I have got to the stage of turning my front wheel servo to 90.
 
When I run "picar servo-install", the terminal prints "servo is now set to 90 degree" but the servo doesn't move and the command doesn't end.

To end the command, I have to use Ctrl+C

$ picar servo-install
Servo now is set to 90 degree.
 
#keyboard input Ctrl+ C
 
Traceback (most recent call last):
  File "/usr/local/bin/picar", line 11, in <module>
    load_entry_point('SunFounder-PiCar==1.0.1', 'console_scripts', 'picar')()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 46, in main
    servo_install()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 40, in servo_install
    time.sleep(1)
KeyboardInterrupt

I initially thought this was an issue with the servo itself, but I have bought a replacement servo and still have the same issue.

I have installed a fresh copy of Debian
I have updated to the latest source code.
I have tried to download the PiCar-V source code and run the "servo-install" command with the same results.

Any help would be appreciat
Regards
Tom Nolan

**Comment by jtchilders** [comment]
I have the same issue with my car. Ran the `picar servo-isntall` ; it prints the message as above and never exits. The servo doesn't move at all. I have rechecked the wiring and everything is correct. 

@rizzle95 did you manage a solution?

**Comment by rizzle95** [comment]
@jtchilders Hi mate,
unfortunately I didn't solve the issue. I did eventually get a response from Sunfounder but their help was too late as I returned the car to Amazon.

I have since deleted their emails too so am unable to tell you exactly what they suggested.

I ended up purchasing an Arduino kit as a replacement and was actually thankful the PiCar was faulty. The Arduino kit suited my needs far more.

If you'd like any more info on the Arduino, let me know.
